# Generated by Django 4.2.30 on 2026-06-02 06:52

from django.db import migrations, models
import pgvector.django.vector


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge', '0001_enable_pgvector'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.CharField(max_length=255)),
                ('chunk_index', models.IntegerField()),
                ('content', models.TextField()),
                ('content_hash', models.CharField(max_length=32)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1024)),
            ],
            options={
                'db_table': 'knowledge_chunks',
                'indexes': [models.Index(fields=['source_file', 'chunk_index'], name='idx_chunk_lookup')],
                'unique_together': {('source_file', 'chunk_index')},
            },
        ),
    ]
