# Generated by Django 4.2.30 on 2026-06-02 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField()),
                ('assistant_reply', models.TextField()),
                ('intent', models.CharField(choices=[('vip_question', 'VIP Question'), ('exchange_registration', 'Exchange Registration'), ('kol_collaboration', 'KOL Collaboration'), ('support_request', 'Support Request'), ('general_info', 'General Info'), ('unknown', 'Unknown')], max_length=50)),
                ('needs_human_support', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='users.rastaduser')),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='idx_message_user')],
            },
        ),
    ]
