# Generated by Django 4.2.30 on 2026-06-02 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RastadUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('segment', models.CharField(choices=[('new_user', 'New User'), ('vip_interest', 'VIP Interest'), ('exchange_signup', 'Exchange Signup'), ('kol_candidate', 'KOL Candidate'), ('support_needed', 'Support Needed'), ('general_question', 'General Question')], default='new_user', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('auth_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rastad_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rastad_users',
            },
        ),
    ]
